### ISSUE TITLE
guix-packaging-insert-input is slow

### ISSUE THREAD

**Issue by Ambrevar** [ryanprior/emacs-guix-packaging#3]
Typing in the minibuffer of guix-packaging-insert-input is very slow.
I believe this is because `guix-packaging--list-available` runs `guix` on every query update.

I suggest the following optimization: store the full list once with guix-packaging--map-tsv-to-plist, then query this plist in `guix-packaging-insert-input` completion-table-dynamic.

**Comment by ryanprior** [comment]
That's interesting, it's fast for me but maybe my ivy completion system is doing some caching for me. I will do some testing in a bare Emacs and get the performance to an acceptable level.

**Comment by Ambrevar** [comment]
I've only tested with Helm.

**Comment by Ambrevar** [comment]
It's blazing fast now, excellent!
