### ISSUE TITLE
Guess Git URI even when not under point

### ISSUE THREAD

**Issue by Ambrevar** [ryanprior/emacs-guix-packaging#4]
It'd be neat if guix-packaging-hash-git could find the Git URI even if not under point.

It shouldn't be hard: 
- Save the excursion.
- Go to the beginning of the definition.
- Search for the first URL forward.

I think this should work in most cases.

**Comment by ryanprior** [comment]
That seems handy. I will research how to search for the first URL forward. Probably there is a standard URL pattern that's part of thing-at-point or something.

**Comment by Ambrevar** [comment]
Alternatively, you can search for `"`, forward char, then call
`thing-at-point url`.
Repeat until it find something within the definition boundaries.
